In [ ]:
import numpy as np
import pickle
from pathlib import Path
from urllib.request import urlretrieve
from os.path import isfile, isdir
from tqdm import tqdm 
import tarfile

cifar10_dataset_folder_path = 'cifar-10-batches-py'

class DownloadProgress(tqdm):
    last_block = 0

    def hook(self, block_num=1, block_size=1, total_size=None):
        self.total = total_size
        self.update((block_num - self.last_block) * block_size)
        self.last_block = block_num

""" 
    check if the data (zip) file is already downloaded
    if not, download it from "https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz" and save as cifar-10-python.tar.gz
"""
if not isfile('cifar-10-python.tar.gz'):
    with DownloadProgress(unit='B', unit_scale=True, miniters=1, desc='CIFAR-10 Dataset') as pbar:
        urlretrieve(
            'https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz',
            'cifar-10-python.tar.gz',
            pbar.hook)

if not isdir(cifar10_dataset_folder_path):
    with tarfile.open('cifar-10-python.tar.gz') as tar:
        tar.extractall()
        tar.close()

CIFAR-10 Dataset: 171MB [00:04, 38.3MB/s]                           


In [ ]:
import numpy as np
  
ini_array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3], [6,7]])
  
# printing initial arrays
print("initial array", str(ini_array1))
  
# Multiplying arrays
result = ini_array1.flatten()
  
# printing result
print("New resulting array: ", result)
# B = np.reshape(result, (-1, 3))
# print(B.tolist())

initial array [list([1, 2, 3]) list([2, 4, 5]) list([1, 2, 3]) list([6, 7])]
New resulting array:  [list([1, 2, 3]) list([2, 4, 5]) list([1, 2, 3]) list([6, 7])]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  This is separate from the ipykernel package so we can avoid doing imports until


In [ ]:
a = [[1, 2, 3], [2, 4, 5], [1, 2, 3], [6,7]]
arr = np.arange(6)
arr.dtype

dtype('int64')

In [ ]:
import numpy as np
  
ini_array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3], [6,7]])
  
# printing initial arrays
print("initial array", str(ini_array1))
  
# Multiplying arrays
result = ini_array1.flatten()
  
# printing result
print("New resulting array: ", result)
# B = np.reshape(result, (-1, 3))
# print(B.tolist())

initial array [list([1, 2, 3]) list([2, 4, 5]) list([1, 2, 3]) list([6, 7])]
New resulting array:  [list([1, 2, 3]) list([2, 4, 5]) list([1, 2, 3]) list([6, 7])]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  This is separate from the ipykernel package so we can avoid doing imports until


In [ ]:
import numpy as np
  
ini_array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3], [6,7]])
  
# printing initial arrays
print("initial array", str(ini_array1))
  
# Multiplying arrays
result = ini_array1.flatten()
  
# printing result
print("New resulting array: ", result)
# B = np.reshape(result, (-1, 3))
# print(B.tolist())

initial array [list([1, 2, 3]) list([2, 4, 5]) list([1, 2, 3]) list([6, 7])]
New resulting array:  [list([1, 2, 3]) list([2, 4, 5]) list([1, 2, 3]) list([6, 7])]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  This is separate from the ipykernel package so we can avoid doing imports until


In [ ]:

import numpy as np
import pickle
from pathlib import Path

# Path to the unzipped CIFAR data
data_dir = Path("cifar-10-batches-py/")

# Unpickle function provided by the CIFAR hosts
def unpickle(file):
    with open(file, "rb") as fo:
        dict = pickle.load(fo, encoding="bytes")
    return dict

images, labels = [], []
for batch in data_dir.glob("data_batch_*"):
    batch_data = unpickle(batch)
    for i, flat_im in enumerate(batch_data[b"data"]):
        im_channels = []
        # Each image is flattened, with channels in order of R, G, B
        for j in range(3):
            im_channels.append(
                flat_im[j * 1024 : (j + 1) * 1024].reshape((32, 32))
            )
        # Reconstruct the original image
        images.append(np.dstack((im_channels)))
        # Save the label
        labels.append(batch_data[b"labels"][i])

# print("Loaded CIFAR-10 training set:")
# print(f" - np.shape(images)     {np.shape(images)}")
# print(f" - np.shape(labels)     {np.shape(labels)}")



array([[[136, 158, 138],
        [134, 157, 135],
        [135, 158, 140],
        ...,
        [107, 127, 109],
        [107, 125, 104],
        [103, 120, 113]],

       [[139, 166, 155],
        [139, 163, 154],
        [135, 156, 142],
        ...,
        [132, 146, 127],
        [130, 143, 125],
        [126, 140, 135]],

       [[129, 148, 121],
        [130, 148, 121],
        [128, 143, 115],
        ...,
        [161, 172, 173],
        [162, 169, 175],
        [159, 169, 171]],

       ...,

       [[132, 142, 143],
        [126, 135, 137],
        [129, 138, 139],
        ...,
        [163, 168, 164],
        [159, 164, 160],
        [161, 166, 163]],

       [[125, 133, 133],
        [133, 141, 141],
        [130, 140, 139],
        ...,
        [165, 170, 166],
        [164, 169, 165],
        [161, 166, 163]],

       [[137, 146, 146],
        [143, 152, 151],
        [140, 150, 148],
        ...,
        [163, 167, 163],
        [160, 165, 161],
        [159, 164, 162]]

In [ ]:
import tensorflow as tf
(train_images, train_labels), _ = tf.keras.datasets.mnist.load_data()
print(train_labels[0])

5


Mounted at /content/drive


In [ ]:
a = [[[210.77, 203.58, 54.11, 42.83], [93.03, 137.01, 27.81, 35.69], [166.21, 215.57, 171.0, 55.4]], [[210.77, 203.58, 54.11, 42.83], [93.03, 137.01, 27.81, 35.69], [166.21, 215.57, 171.0, 55.4]]]
for i in a:
  print(i)

[[210.77, 203.58, 54.11, 42.83], [93.03, 137.01, 27.81, 35.69], [166.21, 215.57, 171.0, 55.4]]
[[210.77, 203.58, 54.11, 42.83], [93.03, 137.01, 27.81, 35.69], [166.21, 215.57, 171.0, 55.4]]


In [ ]:
import h5py
import numpy as np
a,c,d = [],[],[]
# my_list = [[[344.09, 163.63], [194.49, 19.09, 222.33], [540.4, 59.0], [284.32, 151.89]],
#                [[344.06, 163.63], [194.49, 19.07, 222.33], [194.49, 19.07, 222.33, 1.22, 7.99, 8.23], [540.4, 59.9], [284.39, 151.89]]]
my_list = [[[181.28, 249.68, 384.56, 230.32], [118.93, 276.77, 74.35, 51.55]], [[181.28, 249.68, 384.56, 230.32]]]
for i in range(len(my_list)):
  for j in range(len(my_list[i])):
    # for k in range(len(my_list[i][j])):
      # print(my_list[i][j])
      c.append(my_list[i][j])
      a.append(len(my_list[i][j]))
# print(a)
width = np.array(a).max()
b=[]
for i in range(len(c)):
    if len(c[i]) != width:
        x = np.pad(c[i], (0,width-len(c[i])), 'constant',constant_values = 0)
    else:
        x = c[i]
    b.append(x)
b = np.array(b)
print(b)
# width = np.array(l).max()
# print(width)
# f = h5py.File('tester2.hdf5','w')
# dt = h5py.special_dtype(vlen=np.dtype('int32'))


[[181.28 249.68 384.56 230.32]
 [118.93 276.77  74.35  51.55]
 [181.28 249.68 384.56 230.32]]


In [ ]:
zeroes = np.zeros((2,2,2,3))
ones = np.ones((2,2,2,3))
aa = [[[[1, 2, 3], [4, 5, 7]], [[6, 7, 8], [0, 0, 0]]], [[[1, 2, 3], [4, 1, 7]], [[6, 7, 9], [0, 0, 0]]]]
for i, one in enumerate(aa):
  zeroes[i, ...] = one

zeroes

array([[[[1., 2., 3.],
         [4., 5., 7.]],

        [[6., 7., 8.],
         [0., 0., 0.]]],


       [[[1., 2., 3.],
         [4., 1., 7.]],

        [[6., 7., 9.],
         [0., 0., 0.]]]])

In [1]:
import numpy as np
a = [[[1,2,3,4], [4,5], [7]], [[6,7,8]]]
print(a)
print("")
len2 = max((len(i) for i in a))
# print(len2)
lst = []
for i in range(len(a)):
  for j in range(len(a[i])):
    # for k in range(len(a[i][j])):
    lst.append(len(a[i][j]))
# print(l)
width = max(lst)
# print(width)
# # zeroes = np.zeros((2,3,2,3))
z = [0]*width

row = []
for i in range(len(a)):
  # for j in range(len(a[i])):
    if len(a[i]) != len2:
      n_rows = len2 - len(a[i])
      row.append(n_rows)
      for n in range(n_rows):
        a[i].append(z)
      
# print(a)
# print("****", len(a[0]))


# # print(zeroes)
b=[]
for i in range(len(a)):
  for j in range(len(a[i])):
      if len(a[i][j]) != width:
          x = np.pad(a[i][j], (0,width-len(a[i][j])), 'constant',constant_values = 0)
      else:
          x = a[i][j]
      b.append(x)
b = np.array(b)
print(b)



# padded_array = np.zeros((6,4))
# shape = padded_array.shape
# padded_array[:shape[0],:shape[1]] = a
# print(padded_array)




# c = b.tolist()
# print(c)
reshape = b.reshape(2, 1, len2, width)
print(" ")
print(reshape)

# a = []
# for i in range(len(b)):
#     a.append(b[i][0:l[i]])
# a = np.array(a)
# print(a)
# my_list = [[0 for j in range(3)] for i in range(12)]
# print(my_list)

[[[1, 2, 3, 4], [4, 5], [7]], [[6, 7, 8]]]

[[1 2 3 4]
 [4 5 0 0]
 [7 0 0 0]
 [6 7 8 0]
 [0 0 0 0]
 [0 0 0 0]]
 
[[[[1 2 3 4]
   [4 5 0 0]
   [7 0 0 0]]]


 [[[6 7 8 0]
   [0 0 0 0]
   [0 0 0 0]]]]


In [ ]:
import h5py
import numpy as np
# [[[1, 2, 3], [4, 5, 7]], [[6, 7, 8], [5.7.3]]]

# list = [[[1, 2, 3], [4, 5, 7]], [[6, 7, 8], [5,7,3]]]
list = [[1, 2, 3, -1, 4, 5, 2], [6, 7, 8], [5, 7, -1, 7, 9]]
f = h5py.File('tester.hdf5','w')
# grp=f.create_group('list')
# for i,l in enumerate(list):
#     grp.create_dataset(str(i),data=l)

dt = h5py.special_dtype(vlen=np.dtype('int32'))
dataset = f.create_dataset('vlen',data=np.array(list), dtype=dt)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:13: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  del sys.path[0]


AttributeError: ignored

In [ ]:
import h5py
file = h5py.File("tester.hdf5", "r+")
a = file.get('list')
# n1 = a.get('0')[:].tolist()

ac = []
for i in range(2):
  aa = a.get(str(i))[:].tolist()
  ac.append(aa)
print(ac[0])


# def get_all_keys_from_h5(h5_file):
#     res = []
#     for key in h5_file.keys():
#         res.append(key)
#     return res
    
# k = get_all_keys_from_h5(f)
# num_of_items = file[k[2]][:].shape[0]
# print(num_of_items)

[[1, 2, 3], [4, 5, 7]]


In [ ]:
my_list = [[[[312.68, 182.81, 298.4, 178.56], [178.54, 191.3, 461.09, 288.64], [8.63, 172.4, 286.92, 241.62], 
           [2.38, 5.35, 637.62, 469.3], [2.49, 162.08, 82.29, 244.36], [96.25, 1.88, 108.75, 244.99]], 
           [[308.47, 24.58, 296.9, 399.08], [258.45, 176.1, 110.89, 212.62], [167.21, 172.92, 15.22, 10.24]],
            [[91.43, 191.39, 70.23, 62.73], [319.21, 489.31, 25.63, 29.15], [50.73, 483.15, 19.42, 23.37], 
             [173.59, 473.37, 6.28, 12.11], [44.28, 472.44, 4.26, 11.65], [33.14, 471.2, 5.15, 13.32], [37.28, 472.16, 3.01, 12.29],
             [232.91, 479.38, 4.44, 6.86], [84.21, 445.96, 13.64, 4.19], [27.05, 477.67, 5.84, 8.17], [31.63, 479.59, 2.87, 2.22],
             [333.48, 471.07, 7.42, 13.25], [10.08, 471.68, 7.02, 12.35]]],[[[312.68, 182.81, 298.4, 178.56], [178.54, 191.3, 461.09, 288.64], [8.63, 172.4, 286.92, 241.62], 
           [2.38, 5.35, 637.62, 469.3], [2.49, 162.08, 82.29, 244.36], [96.25, 1.88, 108.75, 244.99]], 
           [[308.47, 24.58, 296.9, 399.08], [258.45, 176.1, 110.89, 212.62], [167.21, 172.92, 15.22, 10.24]],[[308.47, 24.58, 296.9, 399.08], [258.45, 176.1, 110.89, 212.62], [167.21, 172.92, 15.22, 10.24]],
            [[91.43, 191.39, 70.23, 62.73], [319.21, 489.31, 25.63, 29.15], [50.73, 483.15, 19.42, 23.37], 
             [173.59, 473.37, 6.28, 12.11], [44.28, 472.44, 4.26, 11.65], [33.14, 471.2, 5.15, 13.32], [37.28, 472.16, 3.01, 12.29],
             [232.91, 479.38, 4.44, 6.86], [84.21, 445.96, 13.64, 4.19], [27.05, 477.67, 5.84, 8.17], [31.63, 479.59, 2.87, 2.22],
             [333.48, 471.07, 7.42, 13.25], [10.08, 471.68, 7.02, 12.35]]]]
# print(len(my_list))
f = h5py.File('tester22.hdf5','w')
grp=f.create_group('list_of_lists')
for i,list in enumerate(my_list):
    grp.create_dataset(str(i),data=list)

/usr/local/lib/python3.7/dist-packages/h5py/_hl/base.py:118: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  data = np.asarray(data, order="C", dtype=as_dtype)


TypeError: ignored

In [ ]:
aa = {"seg": {"counts": [1,2,3,4], "size": [5,7]}, "segs": [[5,6,7,8], [6,9]]}
for key,value in aa.items():
  for k in value:
    if k != "counts" and k != "size":
      print(k)

[5, 6, 7, 8]
[6, 9]


In [ ]:
aa = [[[[1, 2, 3], [4, 5]], [[6, 7, 8]]]]
print(np.array(aa))

[[[[1 2 3]
   [4 5 0]]

  [[0 0 0]
   [0 0 0]]

  [[6 7 8]
   [0 0 0]]]]


In [ ]:
import itertools
# lst = [[[1, 2, 3], [4, 5, 2]], [[6, 7, 8]], [[5,7],[7,9]]]

lst = [[[1, 2, 3, 4], [4, 5], [7]], [[6, 7, 8]]]
# flat = [element for sublist in original_list for element in sublist]
a,b = [],[]
for i in range(len(lst)):
  if len(lst[i]) != 1:
    for j in range(len(lst[i])):
      lst[i][j].append(-1)
    # print(lst[i])
    aa = [k for row in lst[i] for k in row]
    a.append(aa)
  else:
    a.append(list[i][0])

  
# print(my_list)
# aa = [1,2,3,4]
# for i, a in enumerate(aa):
#   aa[i] = 5
print(a)

[[1, 2, 3, 4, -1, 4, 5, -1, 7, -1], [6, 7, 8]]


In [ ]:
my_list = [[1, 2, 3, -1, 4, 5, 2, -1], [6, 7, 8], [5, 7, -1, 7, 9, -1]]
# my_list = [[[1, 2, 3, 4], [4, 5], [7]], [[6, 7, 8]]]

for row in my_list:
  if row[-1] == -1:
    row.pop()
print(my_list)

[[1, 2, 3, -1, 4, 5, 2], [6, 7, 8], [5, 7, -1, 7, 9]]


In [ ]:
def mySplit(my_list, sep):
    result = []
    sepcount = 0
    current_output = []
    for i, elem in enumerate(my_list):
        if elem != sep:
            sepcount = 0
            current_output.append(elem)
            if (i==(len(my_list)-1)):
                result.append(current_output)
        else:
            if current_output: 
                result.append(current_output)
                current_output = []

            sepcount+=1

            if (i==0) or (sepcount > 1):
                result.append([])
            if (i==(len(my_list)-1)):
                result.append([])

    return result
ac = []
for lst in my_list:
    aa = mySplit(lst, sep=-1)
    ac.append(aa)
ac

[[[1, 2, 3], [4, 5, 2]], [[6, 7, 8]], [[5, 7], [7, 9]]]

In [ ]:
import math
total_tfrecords = 14
num_images = 22439
num_per_shard = int(math.ceil(num_images / total_tfrecords))
num_per_shard

1603

In [ ]:
import numpy as np

import numpy
x = numpy.arange(27)
print(x)
l = numpy.array_split(x,6)
print(l)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]
[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14]), array([15, 16, 17, 18]), array([19, 20, 21, 22]), array([23, 24, 25, 26])]
